repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/python-poetry/poetry
    rev: '1.5.1'  # TODO: py37: Upgrade to latest
    hooks:
      - id: poetry-check
      - id: poetry-lock  # TODO: py37: This step will be redundant once we use poetry 1.6.0+. Remove it
        args: ["--check"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.0.291'
    hooks:
      - id: ruff
        args: [--fix, --fixable, I, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        pass_filenames: false
        language: system
        entry: poetry run mypy .
