version: 2.1

executors:
  default:
    machine:
      image: ubuntu-2404:2024.11.1
      docker_layer_caching: true
    environment:
      BUILDKIT_PROGRESS: plain
      DOCKER_BUILDKIT: 1

workflows:
  ci:
    jobs:
      - test

jobs:
  test:
    executor: default
    steps:
      - checkout
      - restore_cache:
          name: Restore uv cache
          keys:
            - venv-v1-{{ checksum "uv.lock" }}
            - venv-v1-
            - venv-
      - restore_cache:
          name: Restore pre-commit cache
          keys:
            - pre-commit-v1-{{ checksum ".pre-commit-config.yaml" }}
            - pre-commit-v1-
            - pre-commit-
      - run:
          name: Install uv and pre-commit
          command: pip3 install uv pre-commit
      - run:
          name: Install project dependencies
          command: make install
      - run:
          name: Run Linters
          command: make lint
      - run:
          name: Run Tests
          command: |
            export PYTEST_ADDOPTS="--junit-xml=test-results/junit.xml --color=yes"
            make test
      - store_test_results:
          path: test-results
      - save_cache:
          name: Save uv cache
          key: venv-v1-{{ checksum "uv.lock" }}
          paths:
            - "~/.cache/uv"
      - save_cache:
          name: Save pre-commit cache
          key: pre-commit-v1-{{ checksum ".pre-commit-config.yaml" }}
          paths:
            - "~/.cache/pre-commit"
