version: 2.1

executors:
  default:
    machine:
      image: ubuntu-2204:2023.10.1
      docker_layer_caching: true
    environment:
      BUILDKIT_PROGRESS: plain
      DOCKER_BUILDKIT: 1

workflows:
  ci:
    jobs:
      - test

jobs:
  test:
    executor: default
    steps:
      - checkout
      - restore_cache:
          name: Restore uv cache
          keys:
            - uv-v1-{{ checksum "uv.lock" }}
            - uv-v1-
      - restore_cache:
          name: Restore pre-commit cache
          keys:
            - pre-commit-v1-{{ checksum ".pre-commit-config.yaml" }}
            - pre-commit-v1-
      - run:
          name: Install uv
          command: |
            curl -LsSf https://astral.sh/uv/install.sh | sh
      - run:
          name: Install pre-commit
          command: uv tool install pre-commit
      - run:
          name: Install project dependencies
          command: make install
      - run:
          name: Run Linters
          command: |
            export PATH="${HOME}/.local/bin:$PATH"
            make lint
      - run:
          name: Run Tests
          command: |
            export PYTEST_ADDOPTS="--junit-xml=test-results/junit.xml --color=yes"
            make test
      - store_test_results:
          path: test-results
      - save_cache:
          name: Save uv cache
          key: uv-v1-{{ checksum "uv.lock" }}
          paths:
            - "~/.cache/uv"
      - save_cache:
          name: Save pre-commit cache
          key: pre-commit-v1-{{ checksum ".pre-commit-config.yaml" }}
          paths:
            - "~/.cache/pre-commit"
